#加密配置
jasypt:
    encryptor:
        password: widemex
        
server:
    tomcat:
        max-threads: 500
        min-spare-threads: 50

spring:
    redis:
        remote: false
        host: localhost
        port: 6379
        password:
    rabbitmq:
        host: localhost
        port: 5672
        username: dp
        password: widemex
    http:
        multipart:
            max-file-size: 1000MB
            max-request-size: 1000MB
        