#加密配置
jasypt:
    encryptor:
        password: widemex
        
server:
    tomcat:
        max-threads: 500
        min-spare-threads: 50

spring:
    redis:
        remote: false
        host: localhost
        port: 6379
        password:
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
    http:
        multipart:
            max-file-size: 1000MB
            max-request-size: 1000MB
        
# Swagger
swagger:
  title: WideMex dp Swagger API
  description: dp Api Documentation
  version: 1.0.0
  termsOfServiceUrl: 
  contact:
    name: widemex
    url: http://widemex.com.cn
    email: 