server:
   port: 8002

spring:
   datasource:
          url: jdbc:mysql://localhost:3306/widesuite1?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
          username: root
          password: 123456
ignore:
  urls:
    - /authentication/**
    - /**/*.css
    - /social
    - /signin
    - /signup
    - /info
    - /health
    - /metrics/**
    - /loggers/**
    - /mobile/token